[package]
name = "jito-protos"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bincode = "1.3.3"
bytes = "1.9.0"
prost = "0.13"
prost-types = "0.13"
solana-perf = "=2.1.7"
solana-sdk = "=2.1.7"
tonic = "0.12"

[build-dependencies]
tonic-build = "0.12"
